### ISSUE TITLE
Enable authenticated beacon node endpoint

### ISSUE THREAD

**Issue by barnabasbusa** [dapplion/beacon-metrics-gazer#1]
It would be great if the url argument/options would accept authentication header arguments. 

E.g:

```sh
beacon-metrics-gazer --ranges {"0..100": "lh-geth-0", "100..200": "lh-geth-1"} --auth.header ["CF-Access-Client-Id: abc", "CF-Access-Client-Secret: cba"] https://beacon.sepolia.na1.ethpandaops.io
```

**Comment by dapplion** [comment]
Implemented with https://github.com/dapplion/beacon-metrics-gazer/commit/000d390df955a1f7c64375fc2c5251ed932d0b54
