### ISSUE TITLE
Dencun support

### ISSUE THREAD

**Issue by barnabasbusa** [dapplion/beacon-metrics-gazer#3]
On the 4844-devnet-6 I was able to produce this error:

```shell
Caused by:
    range end out of bounds: 2687252 > 103
error fetching state: previous_epoch_participation_offset_offset out of bounds
```
State parser probably need to be updated in order to be able to parse dencun state.

**Comment by dapplion** [comment]
Uploading state from devnet6

[devnet6_finalized_state.zip](https://github.com/dapplion/beacon-metrics-gazer/files/11748235/devnet6_finalized_state.zip)

**Comment by barnabasbusa** [comment]
This has been resolved.
