### ISSUE TITLE
Enable single validator index monitoring + group by value

### ISSUE THREAD

**Issue by barnabasbusa** [dapplion/beacon-metrics-gazer#7]
In order to be able to monitor specific validators based on validator index, it would be great if you could monitor a single validator.

While its currently only possible to do this with this:
```yaml
1000-1001: name
```
Would be good to be able to do:
```yaml
1000: name
```

It would be also good to be able to group by value instead of key. 
As currently it seems like the only the last occurrence of a key:value pair is taken into consideration. 
So one might want to group with something like this:
```yaml
1000: nameA
1010: nameA
1020: nameA
1015: nameB
```

This should return the 2 values, the avgs of `1000,1010,1020` under `nameA` and `1015` under `nameB`.

**Comment by dapplion** [comment]
Suggestion makes sense!

>  the avgs of 1000,1010,1020

So nameA should map to exactly three keys?

**Comment by barnabasbusa** [comment]
Yes, unless other ranges are also defined.
```yaml
1000: nameA
1010: nameA
1020: nameA
1015: nameB
1020-1030: nameA
```

So you could have the avg of `1000+1010+1020+1020-1030`
